2019.10.15

## 数据操作
如果我们无法操作数据，那就寸步难行。通常情况下，我们需要对数据做两方面的操作：

（1）获取数据

（2）处理计算机内存中的数据

如果我们不知道如何存储数据，那谈论获取数据就毫无意义。所以首先让我们来玩一些人造的数据。

我们首先会介绍tensor，它是Pytorch用来存储和处理数据的基本数据类型，它的设计和Numpy的多维数组很相似。

Tensor支持CPU GUP上的异步计算，且支持自动微分

In [1]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.size()

torch.Size([12])

In [6]:
x = x.reshape((3,4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
#默认初始化
torch.FloatTensor(2,3)

tensor([[0.0000e+00, 0.0000e+00, 1.6816e-44],
        [0.0000e+00, 2.3793e-36, 4.5786e-41]])

In [8]:
torch.Tensor(2,3)

tensor([[2.9259e-20, 4.5786e-41, 2.9259e-20],
        [4.5786e-41, 0.0000e+00, 0.0000e+00]])

In [9]:
torch.empty(2,3)

tensor([[4.7984e+30, 6.2121e+22, 1.8370e+25],
        [1.4603e-19, 2.7517e+12, 7.5338e+28]])

In [10]:
#特殊初始化

In [11]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
#随机初始化
torch.randn(3,4)

tensor([[ 1.0589, -0.2944, -0.4672, -1.0496],
        [ 1.0497, -0.0955,  0.6317,  0.0192],
        [ 0.3077,  0.9733, -0.1601,  1.9759]])

In [18]:
x = torch.tensor([[1,2],[3,4]])
y = torch.ones_like(x) * 2
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x==y)

tensor([[1, 2],
        [3, 4]])
tensor([[2, 2],
        [2, 2]])
tensor([[3, 4],
        [5, 6]])
tensor([[-1,  0],
        [ 1,  2]])
tensor([[2, 4],
        [6, 8]])
tensor([[0, 1],
        [1, 2]])
tensor([[0, 1],
        [0, 0]], dtype=torch.uint8)


In [23]:
x = torch.tensor(x, dtype=torch.float64)
x

/home/kaikai/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [24]:
torch.exp(x)

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5982]], dtype=torch.float64)

In [25]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = x.t()
print(x)
print(y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  4.,  8.],
        [ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.]])


In [28]:
print(x.shape)
print(y.shape)

torch.Size([3, 4])
torch.Size([4, 3])


In [29]:
x.mm(y)

tensor([[ 14.,  38.,  62.],
        [ 38., 126., 214.],
        [ 62., 214., 366.]])

In [30]:
y = x
y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
torch.cat((x,y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [33]:
torch.cat((x,y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]])

In [34]:
x.sum()

tensor(66.)

In [35]:
x.sum(dim=0)

tensor([12., 15., 18., 21.])

In [36]:
x.sum(dim=1)

tensor([ 6., 22., 38.])

In [37]:
x.norm()

tensor(22.4944)

In [46]:
import numpy as np
a_np = np.arange(12)
a_np

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
a_np = a_np.reshape(3,4)
a_np

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a_tensor = torch.from_numpy(a_np)
a_tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [56]:
b_np = a_tensor.numpy()
b_np

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [58]:
#pytorch 的广播机制
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [59]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [60]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [61]:
x[1,2]

tensor(6.)

In [62]:
x[:, 1:3]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

In [63]:
id(y)

140332383891528

In [64]:
#y指向新的地址
y = x+y
id(y)

140332383515704

In [65]:
id(y)

140332383515704

In [66]:
#不会新开辟空间，y指向原地址
y[:] = x + y
id(y)

140332383515704

In [67]:
#不会新开辟空间，y指向原地址
print(id(y))
y += x
print(id(y))

140332383515704
140332383515704


In [68]:
a

tensor([[0],
        [1],
        [2]])

In [69]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [70]:
y

tensor([[ 0.,  4.,  8., 12.],
        [16., 20., 24., 28.],
        [32., 36., 40., 44.]])

In [71]:
c = torch.ones((3,3))
print(c, id(c))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 140332383833904


In [72]:
c = torch.mm(x, x.t()) + c
print(c, id(c))

tensor([[ 15.,  39.,  63.],
        [ 39., 127., 215.],
        [ 63., 215., 367.]]) 140332384144408


In [73]:
c += torch.mm(x, x.t())
print(c, id(c))

tensor([[ 29.,  77., 125.],
        [ 77., 253., 429.],
        [125., 429., 733.]]) 140332384144408


In [76]:
a = torch.ones((2,3,4), dtype=torch.float32)
b = torch.arange(6, dtype=torch.float32).reshape((2,3,1))
print(a)
print(b)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0.],
         [1.],
         [2.]],

        [[3.],
         [4.],
         [5.]]])


In [77]:
a + b

tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]],

        [[4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.]]])