## 线性代数

In [1]:
import torch

#### 标量scalar

In [2]:
x = torch.Tensor([3.0])
y = torch.Tensor([2.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)

tensor([5.])
tensor([1.])
tensor([6.])
tensor([1.5000])
tensor([9.])


In [5]:
x.item()

3.0

#### 向量vector

In [6]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [7]:
x[3]

tensor(3)

#### 长度length，维度dimensionality， 形状 shape

In [8]:
len(x)

4

In [11]:
x.shape

torch.Size([4])

In [12]:
x.size()

torch.Size([4])

n维向量一般是指向量元素个数是n，n维矩阵一般是指矩阵有n个轴;
n维tensor也是指tensor有n个轴，比如一维tensor就是vector，二维tensor就是矩阵。

In [13]:
x = torch.arange(24).reshape((2,3,4))
x.shape

torch.Size([2, 3, 4])

x是一个三维的tensor，有三个轴，每个轴的数据长度分别是2,3,4

#### 元素级别运算

In [22]:
x = torch.arange(24, dtype=torch.float32).reshape((2,3,4))
x

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [23]:
x.sum()

tensor(276.)

In [24]:
torch.sum(x)

tensor(276.)

In [25]:
print(x.mean())
print(torch.mean(x))
print(torch.div(torch.sum(x), torch.numel(x)))

tensor(11.5000)
tensor(11.5000)
tensor(11.5000)


#### 两个向量的点积 dot products

In [27]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
print(x)
print(y)
print(torch.dot(x,y))
print((x*y).sum())

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])
tensor(6.)
tensor(6.)


#### 矩阵和向量乘积 matrix-vector

In [37]:
A = torch.arange(12,dtype=torch.float32).reshape(3,4)
x = torch.arange(4, dtype=torch.float32)
print(A)
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([0., 1., 2., 3.])


In [38]:
torch.mv(A, x)

tensor([14., 38., 62.])

#### 矩阵和矩阵乘法matrix-matrix

In [40]:
print(A)
B = A
print(B)
print(torch.mm(A,B.t()))#矩阵和矩阵乘法
print(A*B)#元素级别乘法

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 14.,  38.,  62.],
        [ 38., 126., 214.],
        [ 62., 214., 366.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])


#### 范数 Norms

In [41]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
#1范数
torch.sum(torch.abs(A))

tensor(66.)

In [43]:
#2范数
torch.norm(A)

tensor(22.4944)