In [44]:
import torch
import numpy as np

#生成训练数据
num_features = 2
num_examples = 1000
true_w = torch.Tensor([2, -3.4])
true_b = 4.2
inputs = torch.zeros(num_examples, num_features).normal_()#正态分布生成给定shape的输入样本
labels = torch.mm(inputs, true_w.reshape(num_features,1)) + true_b#生成GT的labels

In [45]:
#dataloader
from torch.utils.data import DataLoader, Dataset, TensorDataset
def load_torch_array(data_arrays, batch_size, is_train=True):
    dataset = TensorDataset(*data_arrays)
    dataloader = DataLoader(dataset, batch_size, shuffle=True)
    return dataloader
batch_size=10
train_dataloader = load_torch_array((inputs, labels), batch_size)
for X,y in train_dataloader:
    print(X)
    print(y)
    break

tensor([[ 0.7714,  1.1876],
        [-0.5792,  0.0359],
        [ 2.4065,  1.3062],
        [-1.6062,  1.7283],
        [ 0.2489,  1.2175],
        [ 0.8983, -0.7168],
        [-0.5366, -0.3068],
        [ 0.8297,  0.0938],
        [ 0.5796, -0.2179],
        [-1.0034,  1.4588]])
tensor([[ 1.7050],
        [ 2.9195],
        [ 4.5718],
        [-4.8885],
        [ 0.5583],
        [ 8.4335],
        [ 4.1699],
        [ 5.5407],
        [ 6.1000],
        [-2.7668]])


In [62]:
#model
from torch.nn import Module
from torch.nn import Linear
class MyLinearRegressModel(Module):
    def __init__(self):
        super(MyLinearRegressModel, self).__init__()
        self.layer = Linear(2, 1, bias=True)
    def forward(self, x):
        x = self.layer(x)
        return x
net = MyLinearRegressModel()

In [63]:
net

MyLinearRegressModel(
  (layer): Linear(in_features=2, out_features=1, bias=True)
)

In [64]:
#初始化模型参数
net.layer.weight.data=torch.Tensor(np.random.normal(size=(1,2),scale=0.01,loc=0))
net.layer.bias.data=torch.Tensor([0])
print(net.layer.weight)
print(net.layer.bias)

Parameter containing:
tensor([[ 0.0139, -0.0020]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [65]:
print(net.layer.weight)

Parameter containing:
tensor([[ 0.0139, -0.0020]], requires_grad=True)


In [66]:
#优化器
from torch.optim import SGD
optimizer = SGD(net.parameters(), lr=0.001)

In [67]:
#损失函数
from torch.nn import MSELoss
mseloss = MSELoss(reduction='mean')

In [68]:
#训练
epochs = 100
for epoch in range(epochs):
    for x, y in train_dataloader:
        p = net(x)
        l = mseloss(p, y)
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    l_epoch = mseloss(net(inputs), labels)
    print('epoch {}, train loss is {}'.format(epoch+1, l_epoch))

epoch 1, train loss is 22.523990631103516
epoch 2, train loss is 14.935589790344238
epoch 3, train loss is 9.905510902404785
epoch 4, train loss is 6.570267677307129
epoch 5, train loss is 4.358557224273682
epoch 6, train loss is 2.891709327697754
epoch 7, train loss is 1.918757438659668
epoch 8, train loss is 1.2733231782913208
epoch 9, train loss is 0.8450863361358643
epoch 10, train loss is 0.5609484314918518
epoch 11, train loss is 0.37238532304763794
epoch 12, train loss is 0.2472277134656906
epoch 13, train loss is 0.1641523391008377
epoch 14, train loss is 0.10900606960058212
epoch 15, train loss is 0.07239483296871185
epoch 16, train loss is 0.04808414354920387
epoch 17, train loss is 0.031940046697854996
epoch 18, train loss is 0.021218659356236458
epoch 19, train loss is 0.014097712002694607
epoch 20, train loss is 0.009367094375193119
epoch 21, train loss is 0.006224274169653654
epoch 22, train loss is 0.004136277828365564
epoch 23, train loss is 0.002749277977272868
epoch 2